import { NextResponse } from "next/server";

const DEMO_FLEET = [
    { vehicle_id: "TRK-DL-001", timestamp: Date.now() / 1000, latitude: 27.18, longitude: 78.01, fuel_consumed_liters: 3.2, speed_kmph: 62, route_id: "delhi_mumbai", co2_kg: 8.38, status: "NORMAL", deviation_status: "OK", co2_saved_kg: 0.42, load_status: "LADEN", engine_temp_c: 91, tyre_pressure_psi: 38, cargo_type: "Electronics", weather: "Clear", temperature_c: 22, eta_hours: 4.2, eta_status: "ON_TIME", remaining_km: 280 },
    { vehicle_id: "TRK-DL-002", timestamp: Date.now() / 1000, latitude: 26.22, longitude: 78.18, fuel_consumed_liters: 3.8, speed_kmph: 55, route_id: "delhi_mumbai", co2_kg: 9.95, status: "WARNING", deviation_status: "OK", co2_saved_kg: 0.18, load_status: "LADEN", engine_temp_c: 94, tyre_pressure_psi: 36, cargo_type: "Auto Parts", weather: "Haze", temperature_c: 24, eta_hours: 6.1, eta_status: "AT_RISK", remaining_km: 420 },
    { vehicle_id: "TRK-DL-003", timestamp: Date.now() / 1000, latitude: 23.26, longitude: 77.41, fuel_consumed_liters: 2.9, speed_kmph: 68, route_id: "delhi_mumbai", co2_kg: 7.59, status: "NORMAL", deviation_status: "OK", co2_saved_kg: 0.61, load_status: "LADEN", engine_temp_c: 89, tyre_pressure_psi: 39, cargo_type: "Textiles", weather: "Clear", temperature_c: 21, eta_hours: 8.5, eta_status: "ON_TIME", remaining_km: 600 },
    { vehicle_id: "TRK-DL-004", timestamp: Date.now() / 1000, latitude: 22.31, longitude: 73.18, fuel_consumed_liters: 4.1, speed_kmph: 48, route_id: "delhi_mumbai", co2_kg: 10.74, status: "HIGH_EMISSION_ALERT", deviation_status: "DEVIATED", co2_saved_kg: 0.0, load_status: "LADEN", engine_temp_c: 102, tyre_pressure_psi: 34, cargo_type: "Chemicals", weather: "Rain", temperature_c: 28, eta_hours: 3.2, eta_status: "DELAYED", remaining_km: 200 },
    { vehicle_id: "TRK-CB-005", timestamp: Date.now() / 1000, latitude: 12.92, longitude: 79.13, fuel_consumed_liters: 2.1, speed_kmph: 54, route_id: "chennai_bangalore", co2_kg: 5.50, status: "NORMAL", deviation_status: "OK", co2_saved_kg: 0.73, load_status: "LADEN", engine_temp_c: 88, tyre_pressure_psi: 40, cargo_type: "FMCG", weather: "Clear", temperature_c: 23, eta_hours: 2.8, eta_status: "ON_TIME", remaining_km: 180 },
    { vehicle_id: "TRK-CB-006", timestamp: Date.now() / 1000, latitude: 12.52, longitude: 78.21, fuel_consumed_liters: 2.4, speed_kmph: 61, route_id: "chennai_bangalore", co2_kg: 6.28, status: "NORMAL", deviation_status: "OK", co2_saved_kg: 0.55, load_status: "LADEN", engine_temp_c: 90, tyre_pressure_psi: 38, cargo_type: "Auto Components", weather: "Clear", temperature_c: 22, eta_hours: 1.5, eta_status: "ON_TIME", remaining_km: 100 },
    { vehicle_id: "TRK-CB-007", timestamp: Date.now() / 1000, latitude: 12.84, longitude: 78.11, fuel_consumed_liters: 2.8, speed_kmph: 45, route_id: "chennai_bangalore", co2_kg: 7.33, status: "NORMAL", deviation_status: "OK", co2_saved_kg: 0.38, load_status: "LADEN", engine_temp_c: 87, tyre_pressure_psi: 39, cargo_type: "Pharma", weather: "Fog", temperature_c: 5, temperature_breach: true, eta_hours: 2.0, eta_status: "ON_TIME", remaining_km: 140 },
    { vehicle_id: "TRK-KP-008", timestamp: Date.now() / 1000, latitude: 23.68, longitude: 86.97, fuel_consumed_liters: 3.5, speed_kmph: 58, route_id: "kolkata_patna", co2_kg: 9.16, status: "WARNING", deviation_status: "OK", co2_saved_kg: 0.22, load_status: "LADEN", engine_temp_c: 95, tyre_pressure_psi: 37, cargo_type: "Steel Coils", weather: "Clear", temperature_c: 25, eta_hours: 5.0, eta_status: "ON_TIME", remaining_km: 320 },
    { vehicle_id: "TRK-KP-009", timestamp: Date.now() / 1000, latitude: 24.79, longitude: 85.00, fuel_consumed_liters: 3.0, speed_kmph: 64, route_id: "kolkata_patna", co2_kg: 7.85, status: "NORMAL", deviation_status: "OK", co2_saved_kg: 0.48, load_status: "LADEN", engine_temp_c: 92, tyre_pressure_psi: 38, cargo_type: "Cement", weather: "Clear", temperature_c: 24, eta_hours: 2.2, eta_status: "ON_TIME", remaining_km: 150 },
    { vehicle_id: "TRK-KP-010", timestamp: Date.now() / 1000, latitude: 25.10, longitude: 85.14, fuel_consumed_liters: 2.7, speed_kmph: 52, route_id: "kolkata_patna", co2_kg: 7.07, status: "NORMAL", deviation_status: "OK", co2_saved_kg: 0.58, load_status: "LADEN", engine_temp_c: 89, tyre_pressure_psi: 39, cargo_type: "Consumer Goods", weather: "Clear", temperature_c: 23, eta_hours: 1.8, eta_status: "ON_TIME", remaining_km: 120 },
];

export async function GET() {
    return NextResponse.json(DEMO_FLEET);
}
